name: Build
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Install MFC (这步绝对不许删！)
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise" --add Microsoft.VisualStudio.Component.VC.ATLMFC --quiet --norestart
          echo MFC 安装结束，等待完毕
      - name: Build All Projects
        shell: cmd
        run: |
          msbuild "${{ github.workspace }}\Server\Server.vcxproj" /p:Configuration=Release /p:Platform=x64 /p:CharacterSet=MultiByte /p:PreprocessorDefinitions="_CRT_SECURE_NO_WARNINGS;_MBCS" /m
          msbuild "${{ github.workspace }}\Server\TestDll.vcxproj" /p:Configuration=Release /p:Platform=x64 /p:CharacterSet=MultiByte /p:PreprocessorDefinitions="_CRT_SECURE_NO_WARNINGS;_MBCS" /m
      - name: Upload All EXE and DLL
        uses: actions/upload-artifact@v4
        with:
          name: Final_Complete
          path: |
            Server\**\*.exe
            Server\**\*.dll
